# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.srcs/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/matrix_mult_zybo_axi_smc_2.xci
# IP: The module: 'matrix_mult_zybo_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/bd_768e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_0/bd_768e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_1/bd_768e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_2/bd_768e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_3/bd_768e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_4/bd_768e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_5/bd_768e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_6/bd_768e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_7/bd_768e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_8/bd_768e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_9/bd_768e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_10/bd_768e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_11/bd_768e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_12/bd_768e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_1/bd_768e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_1/bd_768e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_5/bd_768e_s00a2s_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_6/bd_768e_sarn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_7/bd_768e_srn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_8/bd_768e_sawn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_9/bd_768e_swn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_10/bd_768e_sbn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_11/bd_768e_m00s2a_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_mult_zybo_axi_smc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_mult_zybo_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.srcs/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/matrix_mult_zybo_axi_smc_2.xci
# IP: The module: 'matrix_mult_zybo_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/bd_768e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_0/bd_768e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_1/bd_768e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_2/bd_768e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_3/bd_768e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_4/bd_768e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_5/bd_768e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_6/bd_768e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_7/bd_768e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_8/bd_768e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_9/bd_768e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_10/bd_768e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_11/bd_768e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_12/bd_768e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_1/bd_768e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_1/bd_768e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_5/bd_768e_s00a2s_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_6/bd_768e_sarn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_7/bd_768e_srn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_8/bd_768e_sawn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_9/bd_768e_swn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_10/bd_768e_sbn_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/bd_0/ip/ip_11/bd_768e_m00s2a_0_ooc.xdc

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_mult_zybo_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_mult_zybo_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
