# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/matrix_mult_zybo/matrix_mult_zybo.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matrix_mult_zybo || ORIG_REF_NAME==matrix_mult_zybo} -quiet] -quiet

# IP: bd/matrix_mult_zybo/ip/matrix_mult_zybo_processing_system7_0_0/matrix_mult_zybo_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matrix_mult_zybo_processing_system7_0_0 || ORIG_REF_NAME==matrix_mult_zybo_processing_system7_0_0} -quiet] -quiet

# IP: bd/matrix_mult_zybo/ip/matrix_mult_zybo_axil_mat_prod1_0_2/matrix_mult_zybo_axil_mat_prod1_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matrix_mult_zybo_axil_mat_prod1_0_2 || ORIG_REF_NAME==matrix_mult_zybo_axil_mat_prod1_0_2} -quiet] -quiet

# IP: bd/matrix_mult_zybo/ip/matrix_mult_zybo_axi_smc_2/matrix_mult_zybo_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matrix_mult_zybo_axi_smc_2 || ORIG_REF_NAME==matrix_mult_zybo_axi_smc_2} -quiet] -quiet

# IP: bd/matrix_mult_zybo/ip/matrix_mult_zybo_rst_ps7_0_100M_2/matrix_mult_zybo_rst_ps7_0_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matrix_mult_zybo_rst_ps7_0_100M_2 || ORIG_REF_NAME==matrix_mult_zybo_rst_ps7_0_100M_2} -quiet] -quiet

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/matrix_mult_zybo_ooc.xdc
