# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.srcs/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axil_mat_prod1_0_2/matrix_mult_zybo_axil_mat_prod1_0_2.xci
# IP: The module: 'matrix_mult_zybo_axil_mat_prod1_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axil_mat_prod1_0_2/constraints/axil_mat_prod1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_mult_zybo_axil_mat_prod1_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.srcs/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axil_mat_prod1_0_2/matrix_mult_zybo_axil_mat_prod1_0_2.xci
# IP: The module: 'matrix_mult_zybo_axil_mat_prod1_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/CoP-HW-SW_2024-2025/Lab0/Vivado_Matrix_Mult/Vivado_Matrix_Mult.gen/sources_1/bd/matrix_mult_zybo/ip/matrix_mult_zybo_axil_mat_prod1_0_2/constraints/axil_mat_prod1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_mult_zybo_axil_mat_prod1_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
