domain_path: C:\GitHub\CoP-HW-SW_2024-2025\Lab0\Vitis\platform_matrix_mult\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
